name: Build & Deploy SyncSnack app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy SyncSnack app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17.0.11

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run:  mvn clean 

